package main

import (
	_ "github.com/xwy2010/go-coinhook/docs" // docs is generated by Swag CLI, you have to import it.
	"github.com/xwy2010/go-coinhook/router"
)

// @title CoinHooks API
// @version 1.0
// @description CoinHooks API.
// @schemes https
// @contact.name Xuwenyu
// @contact.url https://www.coinhooks.io
// @contact.email wenyu.xv@gmail.com

// @license.name Apache 2.0
// @license.url http://www.apache.org/licenses/LICENSE-2.0.html

// @host localhost:1234
// @BasePath /v1

func main() {
	//TODO：热加载配置文件
	// s := make(chan os.Signal, 1)
	// signal.Notify(s, syscall.SIGUSR1)
	// go func() {
	// 	for {
	// 		<-s
	// 		config.ReloadConfig()   //config/conf.go
	// 		log.Println("Reloaded config")
	// 	}
	// }()

	// 执行命令：kill -30 6666  //“6666”为服务器进程号
	router.Run()
}
